# Generated by Django 5.2.1 on 2025-07-26 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_overall_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="product.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="productcolor",
            name="color",
            field=models.CharField(
                choices=[
                    ("#f00", "Red"),
                    ("#a52a2a", "Brown"),
                    ("#00ffff", "Cyan"),
                    ("#ffd700", "Gold"),
                    ("#f5f5dc", "Beige"),
                    ("#ff7f50", "Coral"),
                    ("#4b0082", "Indigo"),
                    ("#000080", "Navy"),
                    ("#000", "Black"),
                    ("#00f", "Blue"),
                    ("#0f0", "Green"),
                    ("#ff0", "Yellow"),
                    ("#ffc0cb", "Pink"),
                    ("#fff", "White"),
                    ("#e6e6fa", "Lavender"),
                    ("#808080", "Gray"),
                    ("#00ff00", "Lime"),
                    ("#ff00ff", "Magenta"),
                    ("#800000", "Maroon"),
                    ("#98ff98", "Mint"),
                    ("#808000", "Olive"),
                    ("#ffa500", "Orange"),
                    ("#800080", "Purple"),
                    ("#fa8072", "Salmon"),
                    ("#c0c0c0", "Silver"),
                    ("#008080", "Teal"),
                    ("#40e0d0", "Turquoise"),
                    ("#ee82ee", "Violet"),
                ],
                max_length=20,
            ),
        ),
    ]
