# Generated by Django 5.2.1 on 2025-07-26 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_alternate_phone_and_more"),
        (
            "product",
            "0002_remove_product_category_idx_alter_product_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "حساب تعريفي",
                "verbose_name_plural": "الملفات الشخصية",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="alternate_phone",
            field=models.CharField(
                blank=True,
                help_text="You can enter another Egyptian phone number for contact (optional).",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="يجب أن يبدأ رقم الهاتف بـ 010، أو 011، أو 012، أو 015 ويتكون من 11 رقمًا.",
                        regex="^(01[0125])[0-9]{8}$",
                    )
                ],
                verbose_name="رقم الهاتف البديل (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "القاهرة"),
                    ("GZ", "الجيزة"),
                    ("ALX", "الإسكندرية"),
                    ("ASN", "أسوان"),
                    ("AST", "أسيوط"),
                    ("BNS", "بني سويف"),
                    ("BH", "البحيرة"),
                    ("IS", "الإسماعيلية"),
                    ("MN", "المنيا"),
                    ("MNF", "المنوفية"),
                    ("MT", "مطروح"),
                    ("KFS", "كفر الشيخ"),
                    ("DK", "الدقهلية"),
                    ("SHG", "سوهاج"),
                    ("SHR", "الشرقية"),
                    ("PTS", "بورسعيد"),
                    ("DT", "دمياط"),
                    ("FYM", "الفيوم"),
                    ("GH", "الغربية"),
                    ("KB", "القليوبية"),
                    ("LX", "الأقصر"),
                    ("WAD", "الوادي الجديد"),
                    ("SUZ", "السويس"),
                    ("SIN", "شمال سيناء"),
                    ("SIS", "جنوب سيناء"),
                    ("QH", "قنا"),
                    ("RSH", "Red Sea"),
                ],
                max_length=15,
                verbose_name="محافظة",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Please enter an Egyptian phone number starting with 010, 011, 012, or 015.",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="يجب أن يبدأ رقم الهاتف بـ 010، أو 011، أو 012، أو 015 ويتكون من 11 رقمًا.",
                        regex="^(01[0125])[0-9]{8}$",
                    )
                ],
                verbose_name="Primary Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True,
                related_name="wishlists",
                to="product.product",
                verbose_name=" قائمة الرغبات",
            ),
        ),
    ]
