# Generated by Django 5.2.1 on 2025-07-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100, verbose_name="place")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Shipping Price"
                    ),
                ),
                (
                    "delivery_time",
                    models.CharField(
                        max_length=100, verbose_name="Estimated Delivery Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Option",
                "verbose_name_plural": "Shipping Options",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_cost",
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="order.shippingoption",
                verbose_name="Shipping Option",
            ),
        ),
    ]
