# Generated by Django 5.2.1 on 2025-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_shippingoption_remove_order_shipping_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Shipping Cost",
            ),
        ),
    ]
