# Generated by Django 5.2.1 on 2025-07-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_shipping_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[("standard", "Standard Shipping")],
                default="standard",
                max_length=20,
                verbose_name="Shipping Method",
            ),
        ),
    ]
